[[constraint]]
  name = "github.com/coreos/etcd"
  version = "3.2.11"

[[constraint]]
  name = "github.com/docktermj/go-logger"
  version = "1.0.3"

[[constraint]]
  name = "github.com/docopt/docopt-go"
  version = "0.6.2"

[[override]]
  name = "github.com/jstemmer/go-junit-report"
  branch = "master"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.0.0"